apiVersion: v1
kind: Service
metadata:
  name: my-springboot-app
  labels:
    app: my-springboot-app
spec:
  selector:
    app: my-springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
