name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-springboot-app:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-springboot-app:latest

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: my-cluster
          location: us-central1-a
      - name: Deploy to GKE
        run: |
          kubectl set image deployment/springboot-app springboot-app=/my-springboot-app:latest
          kubectl rollout status deployment/springboot-app

      #    - name: Run Checkstyle
      #      run: ./gradlew checkstyleMain checkstyleTest

#      - name: Run OWASP Dependency Check
#        uses: dependency-check/Dependency-Check_Action@main
#        with:
#          project: 'spring-boot-ci-cd-demo'
#          path: '.'
#          format: 'HTML'
#          out: 'reports'
#
#      - name: Upload OWASP Report
#        uses: actions/upload-artifact@v4
#        with:
#          name: owasp-report
#          path: reports/
